// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldiyiwihrynrqygvbmhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaXlpd2locnlucnF5Z3ZibWh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzk5MDksImV4cCI6MjA3Mzc1NTkwOX0.ifC7RwDz8SD7iuZQsPmbN58kBhIFzI7a0t7-NV2tDa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});